// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  user_id,
  phone_number,
  gender,
  date_of_birth,
  passport_number,
  identification_number,
  address,
  loyalty_points
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING user_id, phone_number, gender, date_of_birth, passport_number, identification_number, address, loyalty_points, created_at, updated_at
`

type CreateCustomerParams struct {
	UserID               int64       `json:"user_id"`
	PhoneNumber          pgtype.Text `json:"phone_number"`
	Gender               GenderType  `json:"gender"`
	DateOfBirth          pgtype.Date `json:"date_of_birth"`
	PassportNumber       pgtype.Text `json:"passport_number"`
	IdentificationNumber pgtype.Text `json:"identification_number"`
	Address              pgtype.Text `json:"address"`
	LoyaltyPoints        pgtype.Int4 `json:"loyalty_points"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.UserID,
		arg.PhoneNumber,
		arg.Gender,
		arg.DateOfBirth,
		arg.PassportNumber,
		arg.IdentificationNumber,
		arg.Address,
		arg.LoyaltyPoints,
	)
	var i Customer
	err := row.Scan(
		&i.UserID,
		&i.PhoneNumber,
		&i.Gender,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.Address,
		&i.LoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE user_id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCustomer, userID)
	return err
}

const getAllCustomer = `-- name: GetAllCustomer :many
SELECT user_id, phone_number, gender, date_of_birth, passport_number, identification_number, address, loyalty_points, created_at, updated_at FROM customers
`

func (q *Queries) GetAllCustomer(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getAllCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.UserID,
			&i.PhoneNumber,
			&i.Gender,
			&i.DateOfBirth,
			&i.PassportNumber,
			&i.IdentificationNumber,
			&i.Address,
			&i.LoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT user_id, phone_number, gender, date_of_birth, passport_number, identification_number, address, loyalty_points, created_at, updated_at FROM customers
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, userID int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, userID)
	var i Customer
	err := row.Scan(
		&i.UserID,
		&i.PhoneNumber,
		&i.Gender,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.Address,
		&i.LoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT c.user_id, c.phone_number, c.gender, c.date_of_birth, c.passport_number, c.identification_number, c.address, c.loyalty_points, c.created_at, c.updated_at FROM customers c
JOIN users u ON c.user_id = u.user_id
WHERE u.email = $1 LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.UserID,
		&i.PhoneNumber,
		&i.Gender,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.Address,
		&i.LoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT user_id, phone_number, gender, date_of_birth, passport_number, identification_number, address, loyalty_points, created_at, updated_at FROM customers
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.UserID,
			&i.PhoneNumber,
			&i.Gender,
			&i.DateOfBirth,
			&i.PassportNumber,
			&i.IdentificationNumber,
			&i.Address,
			&i.LoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET
  phone_number = $1,
  gender = $2,
  date_of_birth = $3,
  passport_number = $4,
  identification_number = $5,
  address = $6,
  loyalty_points = $7,
  updated_at = NOW()
WHERE user_id = $8
`

type UpdateCustomerParams struct {
	PhoneNumber          pgtype.Text `json:"phone_number"`
	Gender               GenderType  `json:"gender"`
	DateOfBirth          pgtype.Date `json:"date_of_birth"`
	PassportNumber       pgtype.Text `json:"passport_number"`
	IdentificationNumber pgtype.Text `json:"identification_number"`
	Address              pgtype.Text `json:"address"`
	LoyaltyPoints        pgtype.Int4 `json:"loyalty_points"`
	UserID               int64       `json:"user_id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.Exec(ctx, updateCustomer,
		arg.PhoneNumber,
		arg.Gender,
		arg.DateOfBirth,
		arg.PassportNumber,
		arg.IdentificationNumber,
		arg.Address,
		arg.LoyaltyPoints,
		arg.UserID,
	)
	return err
}
