// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flights.sql

package db

import (
	"context"
	"time"
)

const createFlight = `-- name: CreateFlight :one
INSERT INTO flights (
    flight_number,
    aircraft_type,
    departure_city,
    arrival_city,
    departure_airport,
    arrival_airport,
    departure_time,
    arrival_time,
    base_price,
    status
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING flight_id, flight_number, airline, aircraft_type, departure_city, arrival_city, departure_airport, arrival_airport, departure_time, arrival_time, base_price, total_seats_row, total_seats_column, status
`

type CreateFlightParams struct {
	FlightNumber     string       `json:"flight_number"`
	AircraftType     *string      `json:"aircraft_type"`
	DepartureCity    *string      `json:"departure_city"`
	ArrivalCity      *string      `json:"arrival_city"`
	DepartureAirport *string      `json:"departure_airport"`
	ArrivalAirport   *string      `json:"arrival_airport"`
	DepartureTime    time.Time    `json:"departure_time"`
	ArrivalTime      time.Time    `json:"arrival_time"`
	BasePrice        int32        `json:"base_price"`
	Status           FlightStatus `json:"status"`
}

func (q *Queries) CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error) {
	row := q.db.QueryRow(ctx, createFlight,
		arg.FlightNumber,
		arg.AircraftType,
		arg.DepartureCity,
		arg.ArrivalCity,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.BasePrice,
		arg.Status,
	)
	var i Flight
	err := row.Scan(
		&i.FlightID,
		&i.FlightNumber,
		&i.Airline,
		&i.AircraftType,
		&i.DepartureCity,
		&i.ArrivalCity,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.TotalSeatsRow,
		&i.TotalSeatsColumn,
		&i.Status,
	)
	return i, err
}

const deleteFlight = `-- name: DeleteFlight :one
DELETE FROM flights
WHERE flight_id = $1
RETURNING flight_id
`

func (q *Queries) DeleteFlight(ctx context.Context, flightID int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteFlight, flightID)
	var flight_id int64
	err := row.Scan(&flight_id)
	return flight_id, err
}

const getAllFlights = `-- name: GetAllFlights :many
SELECT flight_id,
  flight_number,
  aircraft_type,
  departure_city,
  arrival_city,
  departure_time,
  arrival_time,
  base_price,
  status
FROM Flights
`

type GetAllFlightsRow struct {
	FlightID      int64        `json:"flight_id"`
	FlightNumber  string       `json:"flight_number"`
	AircraftType  *string      `json:"aircraft_type"`
	DepartureCity *string      `json:"departure_city"`
	ArrivalCity   *string      `json:"arrival_city"`
	DepartureTime time.Time    `json:"departure_time"`
	ArrivalTime   time.Time    `json:"arrival_time"`
	BasePrice     int32        `json:"base_price"`
	Status        FlightStatus `json:"status"`
}

func (q *Queries) GetAllFlights(ctx context.Context) ([]GetAllFlightsRow, error) {
	rows, err := q.db.Query(ctx, getAllFlights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFlightsRow{}
	for rows.Next() {
		var i GetAllFlightsRow
		if err := rows.Scan(
			&i.FlightID,
			&i.FlightNumber,
			&i.AircraftType,
			&i.DepartureCity,
			&i.ArrivalCity,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.BasePrice,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlight = `-- name: GetFlight :one
SELECT flight_id, flight_number, airline, aircraft_type, departure_city, arrival_city, departure_airport, arrival_airport, departure_time, arrival_time, base_price, total_seats_row, total_seats_column, status
FROM flights
WHERE flight_id = $1
LIMIT 1
`

func (q *Queries) GetFlight(ctx context.Context, flightID int64) (Flight, error) {
	row := q.db.QueryRow(ctx, getFlight, flightID)
	var i Flight
	err := row.Scan(
		&i.FlightID,
		&i.FlightNumber,
		&i.Airline,
		&i.AircraftType,
		&i.DepartureCity,
		&i.ArrivalCity,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.TotalSeatsRow,
		&i.TotalSeatsColumn,
		&i.Status,
	)
	return i, err
}

const getFlightsByStatus = `-- name: GetFlightsByStatus :one
SELECT status
FROM flights
WHERE flight_id = $1
LIMIT 1
`

func (q *Queries) GetFlightsByStatus(ctx context.Context, flightID int64) (FlightStatus, error) {
	row := q.db.QueryRow(ctx, getFlightsByStatus, flightID)
	var status FlightStatus
	err := row.Scan(&status)
	return status, err
}

const listFlights = `-- name: ListFlights :many
SELECT flight_id,
  flight_number,
  airline,
  departure_city,
  arrival_city,
  departure_time,
  arrival_time,
  departure_airport,
  arrival_airport,
  aircraft_type,
  base_price
FROM flights
ORDER BY flight_id
LIMIT $1 OFFSET $2
`

type ListFlightsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFlightsRow struct {
	FlightID         int64     `json:"flight_id"`
	FlightNumber     string    `json:"flight_number"`
	Airline          *string   `json:"airline"`
	DepartureCity    *string   `json:"departure_city"`
	ArrivalCity      *string   `json:"arrival_city"`
	DepartureTime    time.Time `json:"departure_time"`
	ArrivalTime      time.Time `json:"arrival_time"`
	DepartureAirport *string   `json:"departure_airport"`
	ArrivalAirport   *string   `json:"arrival_airport"`
	AircraftType     *string   `json:"aircraft_type"`
	BasePrice        int32     `json:"base_price"`
}

func (q *Queries) ListFlights(ctx context.Context, arg ListFlightsParams) ([]ListFlightsRow, error) {
	rows, err := q.db.Query(ctx, listFlights, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlightsRow{}
	for rows.Next() {
		var i ListFlightsRow
		if err := rows.Scan(
			&i.FlightID,
			&i.FlightNumber,
			&i.Airline,
			&i.DepartureCity,
			&i.ArrivalCity,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.DepartureAirport,
			&i.ArrivalAirport,
			&i.AircraftType,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFlights = `-- name: SearchFlights :many
SELECT flight_id,
  flight_number,
  airline,
  departure_city,
  arrival_city,
  departure_time,
  arrival_time,
  departure_airport,
  arrival_airport,
  aircraft_type,
  base_price
FROM Flights
WHERE departure_city = $1
  AND arrival_city = $2
  AND DATE(departure_time) = $3
`

type SearchFlightsParams struct {
	DepartureCity *string   `json:"departure_city"`
	ArrivalCity   *string   `json:"arrival_city"`
	DepartureTime time.Time `json:"departure_time"`
}

type SearchFlightsRow struct {
	FlightID         int64     `json:"flight_id"`
	FlightNumber     string    `json:"flight_number"`
	Airline          *string   `json:"airline"`
	DepartureCity    *string   `json:"departure_city"`
	ArrivalCity      *string   `json:"arrival_city"`
	DepartureTime    time.Time `json:"departure_time"`
	ArrivalTime      time.Time `json:"arrival_time"`
	DepartureAirport *string   `json:"departure_airport"`
	ArrivalAirport   *string   `json:"arrival_airport"`
	AircraftType     *string   `json:"aircraft_type"`
	BasePrice        int32     `json:"base_price"`
}

func (q *Queries) SearchFlights(ctx context.Context, arg SearchFlightsParams) ([]SearchFlightsRow, error) {
	rows, err := q.db.Query(ctx, searchFlights, arg.DepartureCity, arg.ArrivalCity, arg.DepartureTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFlightsRow{}
	for rows.Next() {
		var i SearchFlightsRow
		if err := rows.Scan(
			&i.FlightID,
			&i.FlightNumber,
			&i.Airline,
			&i.DepartureCity,
			&i.ArrivalCity,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.DepartureAirport,
			&i.ArrivalAirport,
			&i.AircraftType,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlightTimes = `-- name: UpdateFlightTimes :one
UPDATE Flights
SET departure_time = $2,
  arrival_time = $3
WHERE flight_id = $1
RETURNING flight_id,
  departure_time,
  arrival_time
`

type UpdateFlightTimesParams struct {
	FlightID      int64     `json:"flight_id"`
	DepartureTime time.Time `json:"departure_time"`
	ArrivalTime   time.Time `json:"arrival_time"`
}

type UpdateFlightTimesRow struct {
	FlightID      int64     `json:"flight_id"`
	DepartureTime time.Time `json:"departure_time"`
	ArrivalTime   time.Time `json:"arrival_time"`
}

func (q *Queries) UpdateFlightTimes(ctx context.Context, arg UpdateFlightTimesParams) (UpdateFlightTimesRow, error) {
	row := q.db.QueryRow(ctx, updateFlightTimes, arg.FlightID, arg.DepartureTime, arg.ArrivalTime)
	var i UpdateFlightTimesRow
	err := row.Scan(&i.FlightID, &i.DepartureTime, &i.ArrivalTime)
	return i, err
}
