// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flight_seats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlightSeat = `-- name: CreateFlightSeat :one
INSERT INTO flight_seats (
  flight_id,
  flight_class,
  class_multiplier,
  child_multiplier,
  max_row_seat,
  max_col_seat
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING flight_seats_id, flight_id, flight_class, class_multiplier, child_multiplier, max_row_seat, max_col_seat
`

type CreateFlightSeatParams struct {
	FlightID        int64           `json:"flight_id"`
	FlightClass     FlightClassType `json:"flight_class"`
	ClassMultiplier pgtype.Numeric  `json:"class_multiplier"`
	ChildMultiplier pgtype.Numeric  `json:"child_multiplier"`
	MaxRowSeat      int64           `json:"max_row_seat"`
	MaxColSeat      int64           `json:"max_col_seat"`
}

func (q *Queries) CreateFlightSeat(ctx context.Context, arg CreateFlightSeatParams) (FlightSeat, error) {
	row := q.db.QueryRow(ctx, createFlightSeat,
		arg.FlightID,
		arg.FlightClass,
		arg.ClassMultiplier,
		arg.ChildMultiplier,
		arg.MaxRowSeat,
		arg.MaxColSeat,
	)
	var i FlightSeat
	err := row.Scan(
		&i.FlightSeatsID,
		&i.FlightID,
		&i.FlightClass,
		&i.ClassMultiplier,
		&i.ChildMultiplier,
		&i.MaxRowSeat,
		&i.MaxColSeat,
	)
	return i, err
}

const deleteFlightSeat = `-- name: DeleteFlightSeat :exec
DELETE FROM flight_seats
WHERE flight_id = $1
`

func (q *Queries) DeleteFlightSeat(ctx context.Context, flightID int64) error {
	_, err := q.db.Exec(ctx, deleteFlightSeat, flightID)
	return err
}

const getFlightSeat = `-- name: GetFlightSeat :one
SELECT flight_seats_id, flight_id, flight_class, class_multiplier, child_multiplier, max_row_seat, max_col_seat FROM flight_seats
WHERE flight_id = $1 AND flight_class = $2
`

type GetFlightSeatParams struct {
	FlightID    int64           `json:"flight_id"`
	FlightClass FlightClassType `json:"flight_class"`
}

func (q *Queries) GetFlightSeat(ctx context.Context, arg GetFlightSeatParams) (FlightSeat, error) {
	row := q.db.QueryRow(ctx, getFlightSeat, arg.FlightID, arg.FlightClass)
	var i FlightSeat
	err := row.Scan(
		&i.FlightSeatsID,
		&i.FlightID,
		&i.FlightClass,
		&i.ClassMultiplier,
		&i.ChildMultiplier,
		&i.MaxRowSeat,
		&i.MaxColSeat,
	)
	return i, err
}

const listFlightSeats = `-- name: ListFlightSeats :many
SELECT flight_seats_id, flight_id, flight_class, class_multiplier, child_multiplier, max_row_seat, max_col_seat FROM flight_seats
ORDER BY flight_id
LIMIT $1
OFFSET $2
`

type ListFlightSeatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFlightSeats(ctx context.Context, arg ListFlightSeatsParams) ([]FlightSeat, error) {
	rows, err := q.db.Query(ctx, listFlightSeats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightSeat
	for rows.Next() {
		var i FlightSeat
		if err := rows.Scan(
			&i.FlightSeatsID,
			&i.FlightID,
			&i.FlightClass,
			&i.ClassMultiplier,
			&i.ChildMultiplier,
			&i.MaxRowSeat,
			&i.MaxColSeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightSeatsByFlightID = `-- name: ListFlightSeatsByFlightID :many
SELECT flight_seats_id, flight_id, flight_class, class_multiplier, child_multiplier, max_row_seat, max_col_seat FROM flight_seats
WHERE flight_id = $1
`

func (q *Queries) ListFlightSeatsByFlightID(ctx context.Context, flightID int64) ([]FlightSeat, error) {
	rows, err := q.db.Query(ctx, listFlightSeatsByFlightID, flightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightSeat
	for rows.Next() {
		var i FlightSeat
		if err := rows.Scan(
			&i.FlightSeatsID,
			&i.FlightID,
			&i.FlightClass,
			&i.ClassMultiplier,
			&i.ChildMultiplier,
			&i.MaxRowSeat,
			&i.MaxColSeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
