// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: passenger.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPassenger = `-- name: CreatePassenger :one
INSERT INTO passengers (
  booking_id,
  citizen_id,
  passport_number,
  gender,
  phone_number,
  first_name,
  last_name,
  nationality,
  date_of_birth,
  seat_row,
  seat_col
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING passenger_id, booking_id, citizen_id, passport_number, gender, phone_number, first_name, last_name, nationality, date_of_birth, seat_row, seat_col
`

type CreatePassengerParams struct {
	BookingID      string         `json:"booking_id"`
	CitizenID      string         `json:"citizen_id"`
	PassportNumber sql.NullString `json:"passport_number"`
	Gender         string         `json:"gender"`
	PhoneNumber    string         `json:"phone_number"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Nationality    string         `json:"nationality"`
	DateOfBirth    time.Time      `json:"date_of_birth"`
	SeatRow        int32          `json:"seat_row"`
	SeatCol        string         `json:"seat_col"`
}

func (q *Queries) CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, createPassenger,
		arg.BookingID,
		arg.CitizenID,
		arg.PassportNumber,
		arg.Gender,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.Nationality,
		arg.DateOfBirth,
		arg.SeatRow,
		arg.SeatCol,
	)
	var i Passenger
	err := row.Scan(
		&i.PassengerID,
		&i.BookingID,
		&i.CitizenID,
		&i.PassportNumber,
		&i.Gender,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.Nationality,
		&i.DateOfBirth,
		&i.SeatRow,
		&i.SeatCol,
	)
	return i, err
}

const deletePassenger = `-- name: DeletePassenger :exec
DELETE FROM passengers
WHERE passenger_id = $1
`

func (q *Queries) DeletePassenger(ctx context.Context, passengerID int64) error {
	_, err := q.db.ExecContext(ctx, deletePassenger, passengerID)
	return err
}

const getPassenger = `-- name: GetPassenger :one
SELECT passenger_id, booking_id, citizen_id, passport_number, gender, phone_number, first_name, last_name, nationality, date_of_birth, seat_row, seat_col FROM passengers
WHERE passenger_id = $1 LIMIT 1
`

func (q *Queries) GetPassenger(ctx context.Context, passengerID int64) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, getPassenger, passengerID)
	var i Passenger
	err := row.Scan(
		&i.PassengerID,
		&i.BookingID,
		&i.CitizenID,
		&i.PassportNumber,
		&i.Gender,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.Nationality,
		&i.DateOfBirth,
		&i.SeatRow,
		&i.SeatCol,
	)
	return i, err
}

const listPassengers = `-- name: ListPassengers :many
SELECT passenger_id, booking_id, citizen_id, passport_number, gender, phone_number, first_name, last_name, nationality, date_of_birth, seat_row, seat_col FROM passengers
ORDER BY passenger_id
LIMIT $1
OFFSET $2
`

type ListPassengersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPassengers(ctx context.Context, arg ListPassengersParams) ([]Passenger, error) {
	rows, err := q.db.QueryContext(ctx, listPassengers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passenger
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(
			&i.PassengerID,
			&i.BookingID,
			&i.CitizenID,
			&i.PassportNumber,
			&i.Gender,
			&i.PhoneNumber,
			&i.FirstName,
			&i.LastName,
			&i.Nationality,
			&i.DateOfBirth,
			&i.SeatRow,
			&i.SeatCol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
