// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CheckSeatOccupied(ctx context.Context, arg CheckSeatOccupiedParams) (bool, error)
	CountOccupiedSeats(ctx context.Context, arg CountOccupiedSeatsParams) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error)
	CreateAirplane(ctx context.Context, arg CreateAirplaneParams) (Airplane, error)
	CreateAirplaneModel(ctx context.Context, arg CreateAirplaneModelParams) (AirplaneModel, error)
	CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error)
	CreateFlightSeat(ctx context.Context, arg CreateFlightSeatParams) (FlightSeat, error)
	CreateNews(ctx context.Context, arg CreateNewsParams) (News, error)
	CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAirplane(ctx context.Context, registrationNumber string) error
	DeleteAirplaneModel(ctx context.Context, airplaneModelID int64) error
	DeleteAirport(ctx context.Context, airportCode string) error
	DeleteBookings(ctx context.Context, bookingID int64) error
	DeleteFlight(ctx context.Context, flightNumber string) error
	DeleteFlightSeat(ctx context.Context, flightID int64) error
	DeletePassenger(ctx context.Context, passengerID int64) error
	DeletePayment(ctx context.Context, paymentID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetAirplane(ctx context.Context, registrationNumber string) (Airplane, error)
	GetAirplaneModel(ctx context.Context, airplaneModelID int64) (AirplaneModel, error)
	GetAirport(ctx context.Context, airportCode string) (Airport, error)
	GetAllNews(ctx context.Context) ([]News, error)
	GetAllUser(ctx context.Context) ([]User, error)
	GetBooking(ctx context.Context, bookingID int64) (Booking, error)
	GetFlight(ctx context.Context, flightID int64) (Flight, error)
	GetFlightSeat(ctx context.Context, arg GetFlightSeatParams) (FlightSeat, error)
	GetNews(ctx context.Context, newsID int64) (News, error)
	GetPassenger(ctx context.Context, passengerID int64) (Passenger, error)
	GetPayment(ctx context.Context, paymentID int64) (Payment, error)
	GetUser(ctx context.Context, userID int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAirplaneModels(ctx context.Context, arg ListAirplaneModelsParams) ([]AirplaneModel, error)
	ListAirplanes(ctx context.Context, arg ListAirplanesParams) ([]Airplane, error)
	ListAirports(ctx context.Context, arg ListAirportsParams) ([]Airport, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListFlightSeats(ctx context.Context, arg ListFlightSeatsParams) ([]FlightSeat, error)
	ListFlightSeatsByFlightID(ctx context.Context, flightID int64) ([]FlightSeat, error)
	ListFlights(ctx context.Context, arg ListFlightsParams) ([]Flight, error)
	ListNews(ctx context.Context, arg ListNewsParams) ([]News, error)
	ListPassengers(ctx context.Context, arg ListPassengersParams) ([]Passenger, error)
	ListPayment(ctx context.Context, arg ListPaymentParams) ([]Payment, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
