// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
  flight_class,
  price,
  status,
  booking_id,
  flight_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING ticket_id, flight_class, price, status, booking_id, flight_id, created_at, updated_at
`

type CreateTicketParams struct {
	FlightClass FlightClass  `json:"flight_class"`
	Price       int32        `json:"price"`
	Status      TicketStatus `json:"status"`
	BookingID   pgtype.Int8  `json:"booking_id"`
	FlightID    pgtype.Int8  `json:"flight_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.FlightClass,
		arg.Price,
		arg.Status,
		arg.BookingID,
		arg.FlightID,
	)
	var i Ticket
	err := row.Scan(
		&i.TicketID,
		&i.FlightClass,
		&i.Price,
		&i.Status,
		&i.BookingID,
		&i.FlightID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE ticket_id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, deleteTicket, ticketID)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT ticket_id, flight_class, price, status, booking_id, flight_id, created_at, updated_at FROM tickets
WHERE ticket_id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, ticketID int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, ticketID)
	var i Ticket
	err := row.Scan(
		&i.TicketID,
		&i.FlightClass,
		&i.Price,
		&i.Status,
		&i.BookingID,
		&i.FlightID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByFlightId = `-- name: GetTicketByFlightId :many
SELECT ticket_id, flight_class, price, status, booking_id, flight_id, created_at, updated_at FROM tickets
WHERE flight_id = $1
ORDER BY ticket_id
`

func (q *Queries) GetTicketByFlightId(ctx context.Context, flightID pgtype.Int8) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getTicketByFlightId, flightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.TicketID,
			&i.FlightClass,
			&i.Price,
			&i.Status,
			&i.BookingID,
			&i.FlightID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT ticket_id, flight_class, price, status, booking_id, flight_id, created_at, updated_at FROM tickets
ORDER BY ticket_id
LIMIT $1
OFFSET $2
`

type ListTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.TicketID,
			&i.FlightClass,
			&i.Price,
			&i.Status,
			&i.BookingID,
			&i.FlightID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets
SET
  flight_class = $2,
  price = $3,
  status = $4,
  booking_id = $5,
  flight_id = $6,
  updated_at = NOW()
WHERE ticket_id = $1
`

type UpdateTicketParams struct {
	TicketID    int64        `json:"ticket_id"`
	FlightClass FlightClass  `json:"flight_class"`
	Price       int32        `json:"price"`
	Status      TicketStatus `json:"status"`
	BookingID   pgtype.Int8  `json:"booking_id"`
	FlightID    pgtype.Int8  `json:"flight_id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.Exec(ctx, updateTicket,
		arg.TicketID,
		arg.FlightClass,
		arg.Price,
		arg.Status,
		arg.BookingID,
		arg.FlightID,
	)
	return err
}
