// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO "user" (
  first_name,
  last_name,
  hashed_password,
  role,
  email
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at
`

type CreateAdminParams struct {
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	HashedPassword string `json:"hashed_password"`
	Role           string `json:"role"`
	Email          string `json:"email"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Role,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Gender,
		&i.Address,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Email,
		&i.LoyaltyPoints,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
  first_name,
  last_name,
  hashed_password,
  email
) VALUES (
  $1, $2, $3, $4
) RETURNING user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at
`

type CreateUserParams struct {
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	HashedPassword string `json:"hashed_password"`
	Email          string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Gender,
		&i.Address,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Email,
		&i.LoyaltyPoints,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getAllUser = `-- name: GetAllUser :many
SELECT user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at FROM "user"
`

func (q *Queries) GetAllUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Gender,
			&i.Address,
			&i.DateOfBirth,
			&i.PassportNumber,
			&i.IdentificationNumber,
			&i.HashedPassword,
			&i.Role,
			&i.Email,
			&i.LoyaltyPoints,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at FROM "user"
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Gender,
		&i.Address,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Email,
		&i.LoyaltyPoints,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at FROM "user"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Gender,
		&i.Address,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.IdentificationNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Email,
		&i.LoyaltyPoints,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, first_name, last_name, phone_number, gender, address, date_of_birth, passport_number, identification_number, hashed_password, role, email, loyalty_points, updated_at, created_at FROM "user"
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Gender,
			&i.Address,
			&i.DateOfBirth,
			&i.PassportNumber,
			&i.IdentificationNumber,
			&i.HashedPassword,
			&i.Role,
			&i.Email,
			&i.LoyaltyPoints,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE "user"
SET hashed_password = $2
WHERE user_id = $1
`

type UpdatePasswordParams struct {
	UserID         int64  `json:"user_id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.UserID, arg.HashedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET first_name = $1,
    last_name = $2,
    phone_number = $3,
    gender = $4,
    address = $5,
    passport_number = $6,
    identification_number = $7,
    updated_at = NOW()
WHERE user_id = $8
`

type UpdateUserParams struct {
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	PhoneNumber          pgtype.Text `json:"phone_number"`
	Gender               pgtype.Text `json:"gender"`
	Address              pgtype.Text `json:"address"`
	PassportNumber       pgtype.Text `json:"passport_number"`
	IdentificationNumber pgtype.Text `json:"identification_number"`
	UserID               int64       `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Gender,
		arg.Address,
		arg.PassportNumber,
		arg.IdentificationNumber,
		arg.UserID,
	)
	return err
}
